- hosts: all
  become: yes
  roles:
    - common

- hosts: backend-hosts
  become: yes
  roles:
    - postgresql
    - redis
    - backend

- hosts: frontend-hosts
  become: yes
  roles:
    - frontend
